In [1]:
import pandas as pd
df_feb=pd.read_csv('orders_feb.csv')
df_mar=pd.read_csv('orders_mar.csv')
df_jan=pd.read_csv('orders_jan.csv')
df_jan

   order_id        date product  quantity  price
0         1  2024-01-05       A         2   1000
1         2  2024-01-10       B         1   1500
2         3  2024-01-15       A         3   1000
3         4  2024-01-20       C         4    500
4         5  2024-01-25       B         2   1500

In [2]:
df_feb

   order_id        date product  quantity  price
0         6  2024-02-03       A         1   1000
1         7  2024-02-08       C         3    500
2         8  2024-02-12       B         2   1500
3         9  2024-02-18       A         4   1000
4        10  2024-02-25       C         2    500

In [3]:
df_mar

   order_id        date product  quantity  price
0        11  2024-03-02       B         3   1500
1        12  2024-03-06       A         2   1000
2        13  2024-03-11       C         5    500
3        14  2024-03-18       B         1   1500
4        15  2024-03-25       A         3   1000

In [4]:
df=pd.concat([df_jan,df_feb,df_mar])
df

   order_id        date product  quantity  price
0         1  2024-01-05       A         2   1000
1         2  2024-01-10       B         1   1500
2         3  2024-01-15       A         3   1000
3         4  2024-01-20       C         4    500
4         5  2024-01-25       B         2   1500
0         6  2024-02-03       A         1   1000
1         7  2024-02-08       C         3    500
2         8  2024-02-12       B         2   1500
3         9  2024-02-18       A         4   1000
4        10  2024-02-25       C         2    500
0        11  2024-03-02       B         3   1500
1        12  2024-03-06       A         2   1000
2        13  2024-03-11       C         5    500
3        14  2024-03-18       B         1   1500
4        15  2024-03-25       A         3   1000

In [11]:
df['sales_per_product']=df['price']*df['quantity']
df

   order_id        date product  quantity  price  sales_per_product
0         1  2024-01-05       A         2   1000               2000
1         2  2024-01-10       B         1   1500               1500
2         3  2024-01-15       A         3   1000               3000
3         4  2024-01-20       C         4    500               2000
4         5  2024-01-25       B         2   1500               3000
0         6  2024-02-03       A         1   1000               1000
1         7  2024-02-08       C         3    500               1500
2         8  2024-02-12       B         2   1500               3000
3         9  2024-02-18       A         4   1000               4000
4        10  2024-02-25       C         2    500               1000
0        11  2024-03-02       B         3   1500               4500
1        12  2024-03-06       A         2   1000               2000
2        13  2024-03-11       C         5    500               2500
3        14  2024-03-18       B         1   1500               1500
4        15  2024-03-25       A         3   1000               3000

In [12]:
df_result=df.groupby('product')['sales_per_product'].sum().reset_index()
df_result

  product  sales_per_product
0       A              15000
1       B              13500
2       C               7000

In [16]:
!pip install openpyxl
df_result.to_excel('result.xlsx', index=False)

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)